import type { ComponentMeta, ComponentStory } from '@storybook/react';
import { Panel } from '@/components/atoms';
import ListingDetail from '.';

export default {
  title: 'templates/ListingDetail',
  component: ListingDetail,
} as ComponentMeta<typeof ListingDetail>;

export const Default: ComponentStory<typeof ListingDetail> = (args) => (
  <Panel>
    <ListingDetail {...args} />
  </Panel>
);

Default.args = {
  listingDetail: {
    listing: {
      id: 3049,
      user_id: 165,
      agent_id: null,
      assigned_agent_id: 195,
      trade_id: 'T2304180002',
      status: 20,
      listing_title: '반포동 아파트',
      internal_listing_title: '',
      gap_investment: false,
      owner_name: '',
      owner_phone: '',
      realestate_unique_number: '',
      pnu: '1165010700100200043',
      bubjungdong_code: '1165010700',
      road_name_address: '',
      jibun_address: '',
      address_detail: '',
      dong: '',
      ho: '',
      floor: '',
      sido: '서울',
      sigungu: '서초구',
      eubmyundong: '반포동',
      li: '',
      road_name_bonbun: '',
      road_name_bubun: '',
      jibun_bonbun: '',
      jibun_bubun: '',
      building_name: '',
      long: 0,
      lat: 0,
      token: '',
      realestate_type: 10,
      officetel_type: null,
      buy_or_rent: 1,
      quick_sale: true,
      quick_sale_comparative: '',
      trade_price: 1000000000,
      deposit: 0,
      monthly_rent_fee: 0,
      negotiation_target: 0,
      negotiation_or_auction: 1,
      auction_end_days: null,
      auction_end_time: null,
      auction_batch_processed_time: null,
      negotiation_conversion_time: null,
      administrative_fee: 0,
      special_terms: '',
      contract_amount: 100000000,
      contract_amount_negotiable: true,
      interim_amount1: 0,
      interim_amount_negotiable1: false,
      interim_amount_payment_time1: null,
      interim_amount_payment_time1_type: 1,
      interim_amount2: 0,
      interim_amount_negotiable2: false,
      interim_amount_payment_time2: null,
      interim_amount_payment_time2_type: 1,
      interim_amount3: 0,
      interim_amount_negotiable3: false,
      interim_amount_payment_time3: null,
      interim_amount_payment_time3_type: 1,
      remaining_amount: 900000000,
      remaining_amount_payment_time: null,
      remaining_amount_payment_time_type: 1,
      rent_contract_term_year: 0,
      rent_contract_term_month: 0,
      rent_contract_term_negotiable: true,
      rent_end_date: null,
      move_in_date: null,
      move_in_date_type: 1,
      rent_area: '',
      jeonsae_loan: true,
      veranda_extended: false,
      veranda_remodelling: false,
      description: '',
      jeonyong_area: '33',
      gonggeup_area: '33',
      direction: '남',
      floor_description: '저층',
      total_floor: '20',
      toogi_region: '',
      toji_trade_eligible: false,
      room_count: '2',
      bathroom_count: '1',
      storey: '단층',
      agent_selection_expire_time: null,
      agent_assigned_view_time: null,
      agent_completion_expire_time: null,
      cancelled_time: null,
      cancelled_reason: '',
      cancellation_type: 0,
      view_count: 0,
      updated_time: '2023-04-18T10:19:11+09:00',
      created_time: '2023-04-18T10:16:40+09:00',
    },
    is_owner: false,
    chat_room_id: 3057,
    bidding_id: null,
    bidding_status: null,
    visit_user_type: 2,
    display_address: '서울 서초구 신반포로 270',
    quick_sale_comparative: '',
    trade_or_deposit_price: 1000000000,
    monthly_rent_fee: 0,
    agent_summary: {
      profile_image_full_path: 'https://agent-test.negocio.kr/static/media/random_profile_6.62719d411e6cbc3348c4.png',
      name: 'LEE SAM',
      office_name: '쌤리중개사무소',
      address: '경기 성남시 분당구 분당내곡로 155 ',
      cell_phone: '010-2026-2476',
      office_phone: '010-2026-2476',
      registration_number: '111111111111',
      distance_from_listing: 15.045560179729133,
    },
    participator_count: 0,
    is_favorite: false,
    total_parking_count: '6075',
    parking_per_saedae: '1.78',
    active_status_time: '2023-04-18T10:19:11+09:00',
    photos: [],
    danji_photos: [],
    debt_successions: [],
    collaterals: [],
    tags: [],
    options: [],
    biddings_chat_room_created: null,
    biddings_chat_room_not_created: [
      {
        bidding_id: 0,
        is_my_bidding: false,
        nickname: 'SamLee부캐',
        bidding_status: 1,
        trade_or_deposit_price: 0,
        monthly_rent_fee: 0,
        created_time: null,
      },
      {
        bidding_id: 0,
        is_my_bidding: false,
        nickname: '주지홍',
        bidding_status: 1,
        trade_or_deposit_price: 0,
        monthly_rent_fee: 0,
        created_time: null,
      },
    ],
  },
};
