export interface EmojiType {
  type: number;
  name: string;
  icon: string;
}

const emojis: EmojiType[] = [
  { type: 1, icon: '😂', name: 'Face with tears of joy' },
  { type: 1, icon: '❤️', name: 'Red heart' },
  { type: 1, icon: '🤣', name: 'Rolling on the floor laughing' },
  { type: 1, icon: '👍', name: 'Thumbs up' },
  { type: 1, icon: '😭', name: 'Loudly crying face' },
  { type: 1, icon: '🙏', name: 'Folded hands' },
  { type: 1, icon: '😘', name: 'Face blowing a kiss' },
  { type: 1, icon: '🥰', name: 'Smiling face with hearts' },
  { type: 1, icon: '😍', name: 'Smiling face with heart-eyes' },
  { type: 1, icon: '😊', name: 'Smiling face with smiling eyes' },
  { type: 1, icon: '🎉', name: 'Party popper' },
  { type: 1, icon: '😁', name: 'Beaming face with smiling eyes' },
  { type: 1, icon: '💕', name: 'Two hearts' },
  { type: 1, icon: '🥺', name: 'Pleading face' },
  { type: 1, icon: '😅', name: 'Grinning face with sweat' },
  { type: 2, icon: '🔥', name: 'Fire emoji' },
  { type: 2, icon: '☺️', name: 'Smiling face' },
  { type: 2, icon: '🤦', name: 'Person facepalming' },
  { type: 2, icon: '♥️', name: 'Heart suit' },
  { type: 2, icon: '🤷', name: 'Person shrugging' },
  { type: 2, icon: '🙄', name: 'Face with rolling eyes' },
  { type: 2, icon: '😆', name: 'Grinning squinting face' },
  { type: 2, icon: '🤗', name: 'Hugging face' },
  { type: 2, icon: '😉', name: 'Winking face' },
  { type: 2, icon: '🎂', name: 'Birthday cake' },
  { type: 2, icon: '🤔', name: 'Thinking face' },
  { type: 2, icon: '👏', name: 'Clapping hands' },
  { type: 2, icon: '🙂', name: 'Slightly smiling face' },
  { type: 2, icon: '😳', name: 'Flushed face' },
  { type: 2, icon: '🥳', name: 'Partying face' },
  { type: 3, icon: '😎', name: 'Smiling face with sunglasses' },
  { type: 3, icon: '👌', name: 'OK hand' },
  { type: 3, icon: '💜', name: 'Purple heart' },
  { type: 3, icon: '😔', name: 'Pensive face' },
  { type: 3, icon: '💪', name: 'Flexed biceps' },
  { type: 3, icon: '✨', name: 'Sparkles' },
  { type: 3, icon: '💖', name: 'Sparkling heart' },
  { type: 3, icon: '👀', name: 'Eyes' },
  { type: 3, icon: '😋', name: 'Face savoring food' },
  { type: 3, icon: '😏', name: 'Smirking face' },
  { type: 3, icon: '😢', name: 'Crying face' },
  { type: 3, icon: '👉', name: 'Backhand index pointing right' },
  { type: 3, icon: '💗', name: 'Growing heart' },
  { type: 3, icon: '😩', name: 'Weary face' },
  { type: 3, icon: '💯', name: 'Hundred points' },
  { type: 4, icon: '🌹', name: 'Rose' },
  { type: 4, icon: '💞', name: 'Revolving hearts' },
  { type: 4, icon: '🎈', name: 'Balloon' },
  { type: 4, icon: '💙', name: 'Blue heart' },
  { type: 4, icon: '😃', name: 'Grinning face with big eyes' },
  { type: 4, icon: '😡', name: 'Pouting face' },
  { type: 4, icon: '💐', name: 'Bouquet' },
  { type: 4, icon: '😜', name: 'Winking face with tongue' },
  { type: 4, icon: '🙈', name: 'See-no-evil monkey' },
  { type: 4, icon: '🤞', name: 'Crossed fingers' },
  { type: 4, icon: '😄', name: 'Grinning face with smiling eyes' },
  { type: 4, icon: '🤤', name: 'Drooling face' },
  { type: 4, icon: '🙌', name: 'Raising hands' },
  { type: 4, icon: '🤪', name: 'Zany face' },
  { type: 4, icon: '❣️', name: 'Heart exclamation' },
  { type: 5, icon: '😀', name: 'Grinning face' },
  { type: 5, icon: '💋', name: 'Kiss mark' },
  { type: 5, icon: '💀', name: 'Skull' },
  { type: 5, icon: '👇', name: 'Backhand index pointing down' },
  { type: 5, icon: '💔', name: 'Broken heart' },
  { type: 5, icon: '😌', name: 'Relieved face' },
  { type: 5, icon: '💓', name: 'Beating heart' },
  { type: 5, icon: '🤩', name: 'Star-struck' },
  { type: 5, icon: '🙃', name: 'Upside-down face' },
  { type: 5, icon: '😬', name: 'Grimacing face' },
  { type: 5, icon: '😱', name: 'Face screaming in fear' },
  { type: 5, icon: '😴', name: 'Sleeping face' },
  { type: 5, icon: '🤭', name: 'Face with hand over mouth' },
  { type: 5, icon: '😐', name: 'Neutral face' },
  { type: 5, icon: '🌞', name: 'Sun with face' },
  { type: 6, icon: '😒', name: 'Unamused face' },
  { type: 6, icon: '😇', name: 'Smiling face with halo' },
  { type: 6, icon: '🌸', name: 'Cherry blossom' },
  { type: 6, icon: '😈', name: 'Smiling face with horns' },
  { type: 6, icon: '🎶', name: 'Musical notes' },
  { type: 6, icon: '✌️', name: 'Victory hand' },
  { type: 6, icon: '🎊', name: 'Confetti ball' },
  { type: 6, icon: '🥵', name: 'Hot face' },
  { type: 6, icon: '😞', name: 'Disappointed face' },
  { type: 6, icon: '💚', name: 'Green heart' },
  { type: 6, icon: '☀️', name: 'Sun' },
  { type: 6, icon: '🖤', name: 'Black heart' },
  { type: 6, icon: '💰', name: 'Money bag' },
  { type: 6, icon: '😚', name: 'Kissing face with closed eyes' },
  { type: 6, icon: '👑', name: 'Crown' },
  { type: 7, icon: '🎁	', name: 'Wrapped gift' },
  { type: 7, icon: '💥', name: 'Collision' },
  { type: 7, icon: '🙋', name: 'Person raising hand' },
  { type: 7, icon: '☹️', name: 'Frowning face' },
  { type: 7, icon: '😑', name: 'Expressionless face' },
  { type: 7, icon: '🥴', name: 'Woozy face' },
  { type: 7, icon: '👈', name: 'Backhand index pointing left' },
  { type: 7, icon: '💩', name: 'Pile of poo' },
  { type: 7, icon: '✅', name: 'Check mark button' },
  { type: 7, icon: '👋', name: 'Waving hand' },
];

export default emojis;
