declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_NCP_CLIENT_ID: string;
    NEXT_PUBLIC_KAKAO_JS_KEY: string;
    NEXT_PUBLIC_KAKAO_REST_API_KEY: string;
    NEXT_PUBLIC_NEGOCIO_REST_API_BASE_URL: string;
    NEXT_PUBLIC_NEGOCIO_WEBSOCKET_BASE_URL: string;
    NEXT_PUBLIC_NEGOCIO_CHAT_PHOTO: string;
    NEXT_PUBLIC_NAVER_MAP_URL: string;
    NEXT_PUBLIC_APP_ENVIRONMENT: string;
    NEXT_PUBLIC_GA_TRACKING_ID: string;
    NEXT_PUBLIC_GTM_ID: string;
    KAKAO_CLIENT_SECRET: string;
    NEXT_PUBLIC_NEGOCIO_DELETED_PROFILE_IMG_PATH: string;
    NEXT_PUBLIC_NCP_CLIENT_SEARCH_ID: string;
    NEXT_PUBLIC_NCP_CLIENT_SEARCH_PASSWORD: string;
    NEXT_PUBLIC_NEGOCIO_BASE_URL: string;
  }
}
