name: Test Build
on: workflow_dispatch

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 430360552021.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: test-user-pc
  CONTAINER_NAME: test-user-pc
  TASK_DEFINITION_FAMILY: test-user-pc
  ECS_SERVICE_NAME: test-user-pc
  ECS_CLUSTER_NAME: negocio-client-test
  NEGOCIO_BASE_URL: https://test.negocio.kr
  NEGOCIO_REST_API_BASE_URL: https://api-test.negocio.kr
  NEGOCIO_WEBSOCKET_BASE_URL: wss://websocket-test.negocio.kr
  NEGOCIO_APP_ENVIRONMENT: test
  NEGOCIO_AGENT_CLIENT_URL: https://agent-test.negocio.kr/
  NEGOCIO_CHAT_PHOTO: https://negocio-chat-photos.s3.ap-northeast-2.amazonaws.com
  NAVER_MAP_URL: https://map.naver.com/v5/entry/address
  NAVER_SITE_VERIFICATION: 0dcfc4f74a90805357591f76f8a9502813823c2b
  NEGOCIO_DELETED_PROFILE_IMG_PATH: https://negocio-common.s3.ap-northeast-2.amazonaws.com/random_profiles/random_profile_1.png
  GA_TRACKING_ID: G-X5831H4W14
  GTM_ID: GTM-MQPT86G

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set robots.txt
        run: rm -rf ./public/robots.txt && mv ./public/robots_test.txt ./public/robots.txt

      # - name: Set robots.txt
      #   run: rm -rf ./public/robots_prod.txt

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: actor_${{github.actor}}-sha_${{github.sha}}-id_${{github.run_id}}
        run: |
          echo -e " \
          NEXT_PUBLIC_NCP_CLIENT_ID=${{ secrets.NCP_CLIENT_ID }} \n \
          NEXT_PUBLIC_KAKAO_JS_KEY=${{ secrets.KAKAO_JS_KEY }} \n \
          NEXT_PUBLIC_KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }} \n \
          NEXT_PUBLIC_NEGOCIO_BASE_URL=${{ env.NEGOCIO_BASE_URL }} \n \
          NEXT_PUBLIC_NEGOCIO_REST_API_BASE_URL=${{ env.NEGOCIO_REST_API_BASE_URL }} \n \
          NEXT_PUBLIC_NEGOCIO_WEBSOCKET_BASE_URL=${{ env.NEGOCIO_WEBSOCKET_BASE_URL }} \n \
          NEXT_PUBLIC_APP_ENVIRONMENT=${{ env.NEGOCIO_APP_ENVIRONMENT }} \n \
          NEXT_PUBLIC_NEGOCIO_DELETED_PROFILE_IMG_PATH=${{ env.NEGOCIO_DELETED_PROFILE_IMG_PATH }} \n \
          NEXT_PUBLIC_NAVER_SITE_VERIFICATION=${{ env.NAVER_SITE_VERIFICATION }} \n \
          NEXT_PUBLIC_NEGOCIO_CHAT_PHOTO=${{ env.NEGOCIO_CHAT_PHOTO }} \n \
          NEXT_PUBLIC_NAVER_MAP_URL=${{ env.NAVER_MAP_URL }} \n \
          NEXT_PUBLIC_NCP_CLIENT_SEARCH_ID=${{ secrets.NCP_CLIENT_SEARCH_ID }} \n \
          NEXT_PUBLIC_NCP_CLIENT_SEARCH_PASSWORD=${{ secrets.NCP_CLIENT_SEARCH_PASSWORD }} \n \
          KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \n \
          NEXT_PUBLIC_NEGOCIO_AGENT_CLIENT_URL=${{ env.NEGOCIO_AGENT_CLIENT_URL }} \n \
          " > .env
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.TASK_DEFINITION_FAMILY }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_NAME }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: false
